# site settings
title: Konstru
description: Insinööritoimisto Konstru Oy on rakennesuunnittelutoimisto, jonka päätoimialana on korjausrakennesuunnittelu
url: "http://www.konstru.fi"
# baseurl: "/konstru-www"
baseurl: ""
navigation: 
  - /yritys/
  - /yhteystiedot/
  - /rekrytointi/
  - /palvelut/
# - /referenssit/ # special case, HARD-CODED IN header.html
references:
  - title: Korjausrakentaminen
    url: /referenssit/korjausrakentaminen/
  - title: Uudisrakentaminen
    url: /referenssit/uudisrakentaminen/
  - title: Kuntotutkimukset ja -arviot
    url: /referenssit/kuntotutkimukset/
  - title: Muut tutkimukset
    url: /referenssit/muut-tutkimukset/
  - title: Rakennuttaminen
    url: /referenssit/rakennuttaminen/

sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed

# build settings
markdown: redcarpet

include:
  - .nojekyll
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"